fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User

  group:
    group_class:   App\Entity\Group
    group_manager: sonata.user.orm.group_manager

  service:
    user_manager: usermanager

  from_email:
    address: noreply@catrob.at
    sender_name: "No Reply"