
liip_theme:
  themes: ['pocketcode', 'pocketalice', 'pocketgalaxy', 'pocketphiro', 'phirocode', 'luna', 'create@school']
  active_theme: 'pocketcode'

# used to access all themes via php
parameters:
  themes: ['pocketcode', 'pocketalice', 'pocketgalaxy', 'pocketphiro', 'phirocode', 'luna', 'create@school', 'embroidery']