imports:
    - { resource: parameters.yml }

swiftmailer:
#    url: '%env(MAILER_URL)%'
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: ssl
    auth_mode: plain
    spool: { type: memory }
