# ===== Symfony Annotations =====
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{flavor}/


# ===== Themes and flavors =====

catrobat_web_index:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: index
        permanent: false
        flavor: "pocketcode"

catroweb_flavored:
  resource: "routing_flavored.yml"
  prefix:   /{flavor}/
  requirements:
    flavor:  pocketcode|pocketphiro|pocketalice|pocketgalaxy|phirocode|luna|create@school


# ===== FOS User Bundle =====
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /{flavor}

fos_user_security_login:
    path: /login
    defaults:  { _controller: fos_user.security.controller:loginAction }

#redirect the user after a successfully registration
fos_user_registration_confirmed:
    path: /{flavor}/profile


# ===== Sonata Admin Bundle =====   ToDo: All needed?

sonata_user_admin_security:
  resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
  prefix: /admin

sonata_user_admin_resetting:
  resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
  prefix: /admin/resetting

sonata_user_admin_security_logout:
  path: /logout
  defaults: { _controller: "SonataUserBundle:AdminSecurity:logout" }

admin:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /admin

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin