monolog:
    channels: ['upload', 'download_stats']
    handlers:
        upload:
            type: rotating_file
            path: '%kernel.logs_dir%/upload/upload.log'
            level: error
            max_files: 30
            channels: [upload]
        main:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.log'
            level: info
            max_files: 30
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info
        download_stats:
            type:  rotating_file
            path:  '%kernel.logs_dir%/download_stats/download_stats.log'
            level: info
            max_files: 30
            channels: [download_stats]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
